spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  security:
    user:
      name: user
      password: 1234

api:
  endpoint:
    base-url: /api/v1
